---
- hosts: localhost
  gather_facts: false
  vars:
    ovn_pool: default
    ovn_network: default
    ovn_base_image: ovn-base.qcow2
  tasks:
    - include_role:
        name: ovn_base_image

    - include_role:
        name: ovn_guests

- hosts: ovn
  gather_facts: false
  tasks:
    - name: wait for nodes to acquire addresses
      delegate_to: localhost
      command: >-
        ansible-inventory --host {{ inventory_hostname }}
      register: nodecheck
      changed_when: false
      until: >-
        (nodecheck.stdout|from_json).ansible_host|default('')|ipaddr
      retries: 30
      delay: 1

    - meta: refresh_inventory

- hosts: ovn
  tasks:
    - name: ensure inventory has an address for this node
      fail:
        msg: no address available
      when: not ansible_host|ipaddr

    - name: wait for nodes to boot
      wait_for_connection:

- hosts: ovn
  tasks:
    - include_role:
        name: ovn_common_pre

- hosts: ovn_central
  tasks:
    - include_role:
        name: ovn_controller

- hosts: ovn
  tasks:
    - include_role:
        name: ovn_common_post
